language: r
warnings_are_errors: false
sudo: false
script: 
  - Rscript -e "swirl::install_course(\"Exploratory Data Analysis\")"
  - ./check_rmds.sh
cache: packages
r:
  - 3.4.2
r_packages:
  - rmarkdown
  - lintr
  - tidyverse
  - swirl
  - testthat
  - glue
os:
  - linux